### ISSUE TITLE
HTTPException: 405

### ISSUE THREAD

**Issue by yifanHuang129** [Wildric-Auric/MidJourney-Wrapper#45]
I met the following error:

```
PS F:\midjourney\MidJourney-Wrapper> python .\main.py
Ignoring exception in on_connect
Traceback (most recent call last):
  File "C:\Users\yifan\miniconda3\envs\midjourney\lib\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\yifan\miniconda3\envs\midjourney\lib\site-packages\discord\bot.py", line 793, in on_connect
    await self.register_commands()
  File "C:\Users\yifan\miniconda3\envs\midjourney\lib\site-packages\discord\bot.py", line 460, in register_commands
    await self.http.bulk_upsert_command_permissions(
  File "C:\Users\yifan\miniconda3\envs\midjourney\lib\site-packages\discord\http.py", line 338, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 405 Method Not Allowed (error code: 0): 405: Method Not Allowed
Logged in as BoilSheepSheep#7113
```

I tried to ignore it and write prompt in my channel, but I saw:
```
Ignoring exception in command <discord.commands.SlashCommand name=mj_imagine>:
Traceback (most recent call last):
  File "C:\Users\yifan\miniconda3\envs\midjourney\lib\site-packages\discord\commands\core.py", line 110, in wrapped
    ret = await coro(arg)
  File "C:\Users\yifan\miniconda3\envs\midjourney\lib\site-packages\discord\commands\core.py", line 766, in _invoke
    await self.callback(ctx, **kwargs)
  File "F:\midjourney\MidJourney-Wrapper\main.py", line 27, in mj_imagine
    print(response.txt)
AttributeError: 'Response' object has no attribute 'txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yifan\miniconda3\envs\midjourney\lib\site-packages\discord\bot.py", line 520, in process_application_commands
    await ctx.command.invoke(ctx)
  File "C:\Users\yifan\miniconda3\envs\midjourney\lib\site-packages\discord\commands\core.py", line 306, in invoke
    await injected(ctx)
  File "C:\Users\yifan\miniconda3\envs\midjourney\lib\site-packages\discord\commands\core.py", line 116, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: 'Response' object has no attribute 'txt'
```

The in my channel, the problem is looked like this:
![image](https://user-images.githubusercontent.com/51779810/230572273-9b4b0d0e-6362-4717-9baa-b101258ed543.png)

**Comment by bhj8** [comment]
You should try asking GPT first.
My observation is wrong, your robot seems to have failed to log in successfully. If you haven't modified the code, it should be that your robot's token is wrongly written

**Comment by Wildric-Auric** [comment]
It's ```response.text``` instead of ```response.txt```
And for the ignored errors at the beginning, they aren't big deal, I don't know why it occurs on linux. Try updating pycord, it was discussion in #29 at the end.

**Comment by Wildric-Auric** [comment]
Ah sorry, I just noticed that there was a typo in ```main.py``` it is fixed in the commit e4553fb. Now you would have the exact error message showing correctly in the console.

**Comment by jonadshead** [comment]
I have the same issue, i tried updating to response.text but still shows discord.errors.HTTPException: 405 Method Not Allowed (error code: 0): 405: Method Not Allowed

**Comment by Wildric-Auric** [comment]
@jonadshead just ignore that I does not stop the bot

**Comment by nihs269** [comment]
@jonadshead , @yifanHuang129 
You must invite MidJourney Bot join the same server with your Navigator Bot!!

**Comment by ReberMusk** [comment]
Me too, but it's no big deal. can still be used.
